##The website title
name: GNU/Linux User Group
##Markdown processor
markdown: kramdown
##syntax highlighter. change it to pygments
highlighter: pygments
permalink: none

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: 
sass:
  sass_dir: _sass
  style: :compressed
#paginate: 5
#paginate_path: "page:num"
##The website description (to be used in meta tags)
description: Association for Computing Machinery @ University of Illinois at Urbana-Champaign

##Some frequently used keywords on your website
keywords: some, relevant, keywords, for, usage, in metatags

# last modified plugin
gems:
  - jekyll-last-modified-at

##define this for disqus comment support
#disqus: forumname

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: analyticsDomain

##Some commonly used links

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
##comment this if you want full width posts with no sidebar
#sidebar: on
